- src/scm_context.cpp
minifilter 에서  install 중 Instances 와 AltitudeAndFlags 서브키 생성 안됨을 수정
> scm_context 수정 요청

- _MyLib_test.cpp
- src/nt_name_conv.cpp
- src/nt_name_conv.h
monster 프로젝트 
"db의 evt_file에 nt name -> dos name 으로 변환 실패되는 이슈" ( issue #26 ) 와 연관되어
기존 monster에서 구현한 DriveNameTable class를 대체하기 위해 기능을 보강 및 수정했다.
> NameConverter class 기능 추가 및 mup device인 경우 처리로직 강화

- _MyLib_test.vcxproj
- _MyLib_test.vcxproj.filters
- src/curl_client.cpp
- src/curl_client.h
curl을 이용해서 post하는 기능이 여러군데에서 필요하게 되어 공통적으로 쓸수있도록 만들게 되었다.
> curl을 이용해서 post하는 기능 추가 ( issue #9 )

- src/FileInfoCache.cpp
- src/FileInfoCache.h
+ 파일 정보 캐싱 사이즈가 특정 개수(기본값 5000개)이상일 경우
테이블 내에서 삭제("hit_count" 값이 평균 이하 일때)하는 코드 추가
+ 기존 일반 쿼리문에서 "prepared statement"를 사용 하도록 변경
> FileInfoCache 기능 추가

- src/FileInfoCache.cpp
- src/Win32Utils.cpp
- src/Win32Utils.h
> 파일의 보안 정보를 구하는 함수를 추가해야한다. (issue #13)

- _MyLib_test.cpp
- _test_process_token.cpp
- _test_registry_util.cpp
- src/FileInfoCache.cpp
- src/RegistryUtil.cpp
- src/RegistryUtil.h
- src/Win32Utils.cpp
- src/Win32Utils.h
호스트 정보 수집 기능 추가
+ 사용자 목록
+ 설치된 프로그램 목록
프로세스 권한 수집 기능 추가
> 호스트 정보 수집 및 프로세스 권한 수집 기능 추가

- src/Win32Utils.cpp
- src/Win32Utils.h
- get_file_version() 추가
지정된 파일의 버전 정보를 수집하는 함수
> 파일 버전 수집 기능 추가 (issue #16)

- src/Win32Utils.cpp
- src/Win32Utils.h
- is_executable_file_w() 를 filepath와 handle을 받는 함수로 분리한다.
> is_executable_file_w() 분리 (issue #19)

- _MyLib_test.cpp
- src/Win32Utils.cpp
- src/Win32Utils.h
- src/account_info.cpp
- src/account_info.h
+ UnixTimeToFileTime 함수 추가
+ last_logon_kst() 함수 삭제
> UnixTimeToFileTime 함수 추가

- src/log.cpp
- 로그 백업파일 이름 형식 변경
[현재 log backup파일]
2017-12-18_21-09-35.00325.log = Monster.log
2017-12-18_17-34-15.00844.log = MonsterTray.log
[변경]
Monster.log.2017-12-19_18-00-52
MonsterTray.log.2017-12-19_18-00-52
> 로그 백업파일 이름 변경 ( #23 )

- src/log.cpp
- src/log.h
+ set_log_format() 함수 수정
+ log_write_fmt() 함수 수정
> 로그 함수에 현재 시간 출력 기능 추가

- src/net_util.cpp
- src/net_util.h
- get_net_adapters()에서 subnet mask 정보를 추가로 구한다.
- get_broadcast_list_v4() 함수 추가
추가된 subnet mask 정보를 가지고 broadcast 주소를 구하는 함수
> get_net_adapters()에 subnet mask 정보를 추가

- src/net_util.cpp
- src/net_util.h
- cache에 DNS 레코드가 없는 경우에는 log를 안 남기도록 수정
> dns_query() 내에서 실패시 log 정리

- _MyLib_test.cpp
- _test_process_tree.cpp
- src/Win32Utils.cpp
- src/process_tree.cpp
- src/process_tree.h
+ 특정 프로세스(csrss, WmiPrvSE 등)의 정보를 수집 하지 못하는 문제 개선
+ system, idle 프로세스 처리 로직 추가
- system, idle 프로세스 생성 시각을 수집 할 수 없으므로 현재 시각을 생성 시간으로 처리
> build_process_tree() 함수 개선

- src/curl_client.cpp
- src/curl_client.h
curl_client 클래스 수정
+ set timeout option 추가
+ http post request 데이터를 string 참조자로 받은 후 전송 하도록 변경
> curl_client 클래스 수정

- src/Win32Utils.cpp
- src/Win32Utils.h
+ 프로세스 정보 중 다음과 같은 정보를 추가 수집
- integrity level
- token elevated 유무
- token elevation type
> 프로세스 정보 중 다음과 같은 정보를 추가 수집

- src/curl_client.cpp
- src/curl_client.h
curl_client GET/POST 요청시 HTTP Response 코드값을 반환하도록 변경
> curl_client  HTTP Response 코드값 반환 추가

- _MyLib_test.cpp
- src/curl_client.cpp
- src/curl_client.h
+ Curl Client 개선
- HTTP Request Header를 요청할 때마다 추가 할 수 있는 형태로 리팩토링
- Multipart-Form를 사용하여 HTTP File Upload 구현
> Curl Client 개선

- src/curl_client.cpp
+ http multipart form을 사용하여 파일 전송할 때 데이터를 전송 하지 않던 버그 수정
> curl client file upload 버그 수정

- _MyLib_test.cpp
- src/Win32Utils.cpp
- src/Win32Utils.h
> 파일 리소스 정보에서 회사명 수집 코드 추가

- _test_sched_client.cpp
- src/sched_client.cpp
- src/sched_client.h
* _svc 멤버변수 이외의 변수들을 함수 내부에서 사용하고 자원을 해제하도록 수정
> task_sched_client 리팩토링

- _MyLib_test.cpp
- _test_boost.cpp
- test_unique_ptr.cpp
> add trivia test codes

- src/Win32Utils.h
string 객체를 파라미터로 받는 WcsToMbs/MbsToWcs 류 함수 추가
> WcsToMbs, MbsToWcs wrapper 추가

- src/CppSQLite/CppSQLite3.cpp
- src/CppSQLite/CppSQLite3.h
> sqlite3 backup 기능 추가

- _MyLib_test.cpp
- src/Win32Utils.cpp
- src/Win32Utils.h
Test: test_get_file_original_name()
Resloved: N/A
Related: N/A
> feat: resource 영역에서 OriginalFileName 정보 수집

- src/curl_client.cpp
- src/curl_client.h
> feat: curl bearer 인증 추가

- _MyLib_test.cpp
- _test_steady_timer.cpp
- src/steady_timer.h
* SteadyTimer 재시작 실패 이슈 해결
* SteadyTimer 객체포인터 추가
Test: test_steady_timer_restart
Resolved: #88
Related: N/A
> fix: SteadyTimer 재시작 실패 이슈

- _MyLib_test.cpp
- _test_aes256.cpp
- _test_boost_bind.cpp
- _test_std_map.cpp
- _test_steady_timer.cpp
- src/AKSyncObjs.cpp
- src/AirCrypto.cpp
+ vcpkg 관련해서 발생한 컴파일 에러 수정
+ 테스트 코드 수정
+ 지원하지 않는 Openssl 코드 제거
Related: N/A
Resolved: #92
Test:
_test_boost_bind.cpp
_test_std_map.cpp
_test_steady_timer.cpp
_test_aes256.cpp
> feat: vcpkg 업데이트에 따른 코드 수정 
